# Generated by Django 6.0.3 on 2026-05-09 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_product_stockentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - goods not yet picked'), ('picked', 'Goods picked')], default='pending', max_length=10)),
                ('quantity_picked', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('picked_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='stock.product')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='scheme.deposit')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nin', models.CharField(max_length=20, unique=True, verbose_name='NIN')),
                ('phone', models.CharField(max_length=20)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='scheme.schemecustomer'),
        ),
    ]
