# Generated by Django 6.0.3 on 2026-05-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemecustomer',
            old_name='employer',
            new_name='occupation',
        ),
    ]
