# Generated by Django 6.0.4 on 2026-05-04 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('iron_bar', 'Iron Bar'), ('nail', 'Nail'), ('wheelbarrow', 'Wheelbarrow'), ('wire_mesh', 'Wire Mesh'), ('barbed_wire', 'Barbed Wire'), ('iron_sheet', 'Iron Sheet')], max_length=50)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('piece', 'Piece'), ('kg', 'Kilogram'), ('roll', 'Roll'), ('sheet', 'Sheet')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit (pay later)')], default='cash', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_received', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='stock.product')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='stock.supplier')),
            ],
        ),
    ]
