# Generated by Django 6.0.4 on 2026-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_stockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
