# Generated by Django 6.0.4 on 2026-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockentry_storage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit (pay later)'), ('momo', 'Mobile Money')], default='cash', max_length=10),
        ),
    ]
