# Generated by Django 6.0.4 on 2026-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockentry_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_delivered',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
